version: '3'
services:
  log-server:
    image: 207m/mongodb-logger
    ports:
      - "6000:5000"
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}/admin
    depends_on:
      mongo:
        condition: service_healthy

  mongoku:
    image: huggingface/mongoku
    ports:
      - "6001:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 2s
